spring:
 main:
  web-application-type: none
googleCx:

apiKey:
  google:
  bing:
  
baseUrl:
  google: https://www.googleapis.com/customsearch/v1
  bing: https://api.bing.microsoft.com/v7.0/search

